### ISSUE TITLE
SQL Error Duplicate Entry

### ISSUE THREAD

**Issue by blakeiv** [adityachandelgit/BookLore#278]
Hey! 

I've been using BookLore for a few days now without any issue and i'm a big fan of the project, but I just tried to create a second user for a friend and they're having issues logging in. On the webpage I get the following 

```
Data integrity violation: could not execute statement [(conn=100) Duplicate entry 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsYWNoaWV0cmV2IiwidXNlcklkIjoz...' for key 'uq_refresh_token'] [insert into refresh_token (expiry_date,revocation_date,revoked,token,user_id) values (?,?,?,?,?)]; SQL [insert into refresh_token (expiry_date,revocation_date,revoked,token,user_id) values (?,?,?,?,?)]; constraint [uq_refresh_token]
```

and on the container logs I get the below

```
2025-05-16T20:19:53.721+10:00  WARN 1 --- [booklore-api] [nio-8080-exec-3] o.m.jdbc.message.server.ErrorPacket      : Error: 1062-23000: Duplicate entry 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsYWNoaWV0cmV2IiwidXNlcklkIjoz...' for key 'uq_refresh_token'

2025-05-16T20:19:53.722+10:00  WARN 1 --- [booklore-api] [nio-8080-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 1062, SQLState: 23000

2025-05-16T20:19:53.722+10:00 ERROR 1 --- [booklore-api] [nio-8080-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : (conn=100) Duplicate entry 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJsYWNoaWV0cmV2IiwidXNlcklkIjoz...' for key 'uq_refresh_token'
```

I just used the default docker compose file that was in the github. Please let me know if you need anything else!

Thanks

**Comment by adityachandelgit** [comment]
This should be fixed in v.0.7.0. Can you please try again?

**Comment by blakeiv** [comment]
Is there a way in BookLore to see what version I'm on? I just recreated/repulled the image for the container in proxmox and am still receiving the same error. 

I also tried recomposing in terminal to be sure and again, the same issue persists.

**Comment by blakeiv** [comment]
I've just updated again today to the latest version and it seems that my error has resolved. I can now support multiple users properly.

Thanks!
